### PR TITLE
Bilingual 404

### PR DESCRIPTION
**Pull request by evadb**
This PR creates a bilingual 404 page. This will make it simpler to do language switching. I based this page off of the canada.ca bilingual 404 page: 

screen shot 2018-06-04 at 5 11 48 pm

screen shot 2018-06-04 at 5 12 12 pm

### CODE REVIEW

**Comment by obrien-j** [comment]
I'd suggest running this by content review, but I'm thinking we could lose the 404 and still be legit. 404 is a status code for webservers/browsers, we don't really need to display it to a human.

@sboots I'd also be curious about what we can do internally, either via logging of 404's from flask, or from google analytics such that we don't need to ask people to report our bugs for us. 

Suggest stripping out 404, merging this as an initial content, but then pushing it over to design for a common/look and feel on 'Sorreh, we cudnna find yo page' type messaging.

**Comment by evadb** [comment]
@obrien-j I agree that it's something we could likely remove, and I like your idea of flipping it to content & design for better text. I'll merge it in as is for now with the 404 removed, so I have something to work with.

We can definitely log 404s super easily from flask, if google analytics can't do it for us. I'll keep that in mind.

**Comment by sidewalkballet** [comment]
IRCC's 
image

**Comment by evadb** [comment]
screen shot 2018-06-05 at 12 16 06 pm
@obrien-j @sidewalkballet thoughts?

**Comment by sidewalkballet** [comment]
Fine by me.

**Pull request merged**
